name: artifact

on: [push]

env: 
  FILE_NAME: Test

jobs:
  build:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v1
    
    - name: Upload ${{ env.FILE_NAME }}.md
      uses: actions/upload-artifact@v1.0.0 
      with:
        path: ./${{ env.FILE_NAME }}.md

    
    
