name: artifact

on: [push]

env: 
  FILE_NAME: test

jobs:
  build:
    name: Upload a file
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v1
    
    - name: Upload ${{ env.FILE_NAME }}
      uses: actions/upload-artifact@v1.0.0 
      with:
        name: test.md
        path: ./${{ env.FILE_NAME }}

    
    
